baseURL = "fuehldienatur.github.io"
languageCode = "en-us"
title = "Fuehl die Natur"
theme = "themes"
themesDir = "."

rssLimit = 5
paginate = 4

enableEmoji = true

# Enter your tracking code to enable Google Analytics
[services]
  [services.googleAnalytics]
    ID = ""

enableInlineShortcodes = true

[markup.goldmark.renderer]
  unsafe = true

[taxonomies]
  tag = "tags"

#This theme can generate a multi-level menu.
#Use weight= to specify the order of menu items, and parent= to create a submenu item.
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Über Mich"
    url = "/about"
    weight = 1

  [[menu.main]]
    name = "Kurse"
    url = "/courses"
    weight = 1

  [[menu.main]]
    name = "Services"
    url = "/services"
    weight = 1

  [[menu.main]]
    name = "Kontakt"
    url = "/contact"
    weight = 1

# Paramaters for the whole site
[params]
  title = "Fühl die Natur"
  subtitle = ""
  [params.author]
    name = "Daniela"
    email = "test@example.com"
  instant_page = true
  customCSS = ["style.css"]

  [params.favicon]
    #sml = "/example16.png"
    #med = "/example32.png"
    #lge = "example96.png"

  [params.banner]
    image = "img/apfel_baum.jpg"

#  [params.style]
#    googleFonts = ["Cardo", "Crimson+Text", "Merriweather", "Playfair+Display:400,700", "Roboto+Slab"]

  [params.contact]
    #Use this section to automate contact form.
    #Set service to either "netlify", "formspree" or "php"
    #For formspree, please setup an account at https://formspree.io/
    #For netlify, please read https://www.netlify.com/docs/form-handling/
    #
    #If you use netlify, you'll need to set the confirm_page value (otherwise users will see a generic netlify response)
    #If you use formspree, you'll need to set your formspree form_id.
    #
    #If you use php, you need to host this site on a Server capable of running php.
    # Please edit the /static/contact_mail.php file from the exampleSite.
    #service = "netlify" #or "formspree" or "php"
    #confirm_page = "/contact_thanks" #only used by netlify
    # formspree_formid="" #only used by formspree


    [params.footer]
      copyright = ["[CC0 (public domain)](//creativecommons.org/publicdomain/zero/1.0/)",
                   "Design: [HTML5 UP](//html5up.net/alpha)",
                   "[Hugo Port](//gohugo.io) by [Daniel Saunders](//github.com/funkydan2)",
                   "Adjusted for Fühl die Natur - Daniela 2024"
                  ]

